site/www.australia.gov.au/about-government/contact-government/contact-ministers-members-and-senators.html
I've just updated it for the [main minister contact page](https://www.australia.gov.au/about-government/contact-government/contact-ministers-members-and-senators) for now. 
Will do the rest on Monday.
=> Updated PM on contact page

site/www.australia.gov.au/directories/australia/portfolio/finance.html
This pull request, updates the ministers on the [Finance portfolio page](www.australia.gov.au/directories/australia/portfolio/finance.html)
=> Finance Portfolio update

site/www.australia.gov.au/directories/australia/portfolio/finance.html
Update the sidebar contact links to reflect correct titles and point to directory.gov.au
=> Update sidebar contact links for Finance portfolio

site/prod_nginx.conf, site/rewrites.conf, site/stag_nginx.conf
This Pull requests redirects `about-australia/our-country/time` to the page `/about-australia/facts-and-figures/time-zones-and-daylight-saving`. And with the help of @maxious moved around some  nginx files so that they are commonly shared.
=> Redirect and nginx reconfigure

site/www.australia.gov.au/directories/australia/portfolio/infrastructure.html
This pull request updates the Infrastructure, Regional Development and Cities portfolio.
=> Updating the Infrastructure, Regional Development and Cities portfolio

site/www.australia.gov.au/directories/australia/portfolio/homeaffairs.html, site/www.australia.gov.au/directories/australia/portfolio/infrastructure.html
This pull request updates the Home Affairs portfolio
=> Infoupdate for home affairs

site/www.australia.gov.au/directories/australia/csc.html, site/www.australia.gov.au/directories/australia/portfolio/homeaffairs.html, site/www.australia.gov.au/directories/australia/portfolio/infrastructure.html, site/www.australia.gov.au/information-and-services/money-and-tax/superannuation/government-superannuation-schemes.html
This pull request updates the CSC information as per request #3315
=> Infoupdate csc

site/www.australia.gov.au/news-and-social-media/media-releases/media-releases-and-rss-feeds-by-portfolio.html
This Pull request updates PM and a few portfolios on the MRS page
=> MRS page update

site/www.australia.gov.au/content/wills.html, site/www.australia.gov.au/directories/australia/portfolio/finance.html
This pull request updates 
-the word **Sector** to **Service**.
-a 404 link on the wills page
=> Correcting the wording on Finance portfolio

site/www.australia.gov.au/content/proof-of-age-card.html
This pull request updates a broken link to NSW RMS.
=> Fixed broken link

site/nginx.conf
Destination: https://osb.homeaffairs.gov.au/
=> Added short URL redirect for /zerochance

site/public/index.html
Campaigns being removed for being out of date, and in preparation for caretaker.
=> Removing campaigns as requested by CAB

site/nginx.conf
Merging robots.txt changes into production.
=> SEO de-optimisation

site/public/about-australia/facts-and-figures/time-zones-and-daylight-saving.html
Added Norfolk, Christmas and Cocos Islands
Added UTC relative column to tables
Made code more readable
=> Update timezone information

site/public/about-australia/facts-and-figures/time-zones-and-daylight-saving.html, site/public/about-government/publications/australian-government-gazettes.html
Added Christmas, Norfolk and Cocos (Keeling) Islands
=> Adding timezones for island territories

site/public/profiles/gsecms/themes/ausgovau_bootstrap/favicons/manifest.json
Refer: https://developers.google.com/web/fundamentals/web-app-manifest/#key_manifest_properties
=> Added mandatory fields

site/public/about-australia/special-dates-and-events/public-holidays.html, site/public/profiles/gsecms/modules/contrib/google_analytics/googleanalytics.js
=> Update Tasmanian public holidays

site/public/information-and-services/culture-and-arts/cultural-institutions.html
Adding Royal Australian Mint to cultural institutions page and general page cleanup
=> Add cultural institutions ra mint

site/public/information-and-services/public-safety-and-law/emergency-services.html, site/public/information-and-services/security-and-defence/national-security.html
Correcting hyperlink as previous link 404's.
=> Updating emergency management link

site/public/information-and-services/business-and-industry/abn-acn-business-management.html, site/public/information-and-services/money-and-tax/tax/abn-australian-business-number.html, site/public/news-and-social-media/apps.html
=> Fixes for ATO

site/public/about-government/government-and-parliament.html, site/public/about-government/how-government-works.html
Updating links and wording for how government works and constitution
=> Updates for PEO

site/public/index.html
This pull request replaces the GA snippet with a GTM tracking tag. Allows us to capture various metrics moving forward
=> Adding GTM to homepage

site/public/index.html
=> Trimmed intro text.

site/public/index.html
=> Updated red alert text

site/public/index.html
Updated essential information section.
=> Updated essential information

site/public/index.html
=> Updated essential item list

.circleci/config.yml, .gitignore, purge-cache.sh
This reverts commit 754bd7834e28f265c2c60e72361b6ba8095ec11e, reversing
changes made to f062468dd2afcfc8fc2f21ca8dd78cbe1fc41504.
=> Revert "Merge pull request #147 from govau/cache-purging"

site/public/index.html
Removed symptom checker param for healthdirect.gov.au link
=> Removed symptom checker param

.circleci/config.yml, .gitignore, download.sh, purge-cache.sh
Now with the version of the bash environment commands from deploy.sh which should work on CircleCI...
=> Add automatic homepage cache purging v2

site/public/index.html
Essential info: stimulus package
=> Essential info: stimulus package

site/public/index.html
Stimulus package point relocated
=> Stimulus package point relocated

site/public/index.html
=> Stimulus 'Read more'.

site/public/index.html
=> Stage 1 restrictions update.

site/public/index.html
Stage 1 restrictions - style and link update
=> Stage 1 restrictions - style and link update

site/public/index.html
=> Stage 1 restrictions text

site/public/index.html
Accommodation exclusions noted
=> Accommodation exclusions noted

site/public/index.html
Hero sub-text and page metadata revised
=> Hero sub-text and page metadata revised

site/public/index.html
=> Content tweaks

site/public/index.html
=> Minor stylistic revisions

site/public/index.html
Simple list of state and territory portals
=> Simple list of state and territory portals

site/public/index.html
=> New essential info point

site/public/index.html
=> Updated SA link

site/public/index.html
=> SA link update

site/public/index.html
=> Added text message info line

site/public/index.html
=> Fixed broken health URL

site/public/index.html
Updated essential item bulletin
=> Updated essential item bulletin

site/public/index.html
Link not updated in previous commit.
See Kim's email at 6:23pm.
=> Updated protecting yourself link

site/public/index.html
=> Social Media link update

site/public/index.html
=> Update "at risk" text

site/public/index.html
=> Update to "at risk" information card

site/public/index.html
=> Added new quarantine measure

site/public/index.html
=> Clarified wording

site/public/index.html
=> Additional essential changes

site/public/index.html
=> Removing line break

site/public/index.html
=> New app links

site/public/index.html
=> Undo the addition of app links

site/public/homepage-resources/analytics.js, site/public/index.html
capture carousel data, send to data layer
=> GTM script

site/public/index.html
=> R12 29032020

site/public/index.html
=> Last minute changes before form push

site/public/homepage-resources/style.css
also re adjust icons to meet
https://www.w3.org/WAI/WCAG21/Understanding/target-size.html
=> Icon re align

site/public/index.html
=> Update to essential info

site/public/index.html
=> correcting meta og reference 

site/public/index.html
=> additional essential info points

.circleci/config.yml, cleanup-preview-deploys.sh, config/stag_manifest.yml, preview-deploy.sh, slack.py, undeploy_closed_branches.py
Plus add slack notifications for new preview environments and new deploys to develop/master
=> Deploy and undeploy preview environments for active branches

site/public/index.html, site/public/privacy.html
Content updates and fix to broken contact us link.
=> R24 14042020

site/public/coronavirus-updates.html, site/public/index.html
=> Release 31 content updates 

site/public/about-australia/special-dates-and-events/public-holidays.html
Source (accessed 23 April 2020): https://www.cmtedd.act.gov.au/communication/holidays
=> Add Public Holiday for 27 April 2020 in ACT

site/public/news-and-social-media/apps.html, site/public/news-and-social-media/social-media/facebook.html, site/public/news-and-social-media/social-media/linkedin.html, site/public/news-and-social-media/social-media/twitter.html, site/public/news-and-social-media/social-media/youtube.html
=> Social media and apps update for Services Australia

site/nginx.conf
Redirect old style manual page to https://stylemanual.gov.au/
=> Add stylemanual redirect

site/nginx.conf
=> Remove link to Canberra Create Your Future

site/public/news-and-social-media/social-media/facebook.html, site/public/news-and-social-media/social-media/twitter.html
Removed "Update" social media links. 
Closes #449
=> Changes as requested by service Australia

site/public/about-australia/special-dates-and-events/public-holidays.html
https://twitter.com/timpoliti/status/1358964868712259591
=> Updated public holiday dates to match official state sources

site/public/about-australia/special-dates-and-events/public-holidays.html
https://twitter.com/timpoliti/status/1358964868712259591
=> Public holiday content fixes
